<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="/user/auth">
    <div>
        <label>
            <span>Email</span>
            <input type="text" name="email">
        </label>
    </div>
    <div>
        <label>
            <span>Password</span>
            <input type="password" name="password">
        </label>
    </div>
    <button type="submit">Login</button>
</form>

</body>
</html>