<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Мной загружено</h1>
<form method="post" enctype="multipart/form-data" action="/user/uploadFile">
    <div>
        <label>
            <span>Аватар</span>
            <input type="file" accept="image/*" class="form-control-file" id="avatar" name="avatar">
        </label>
    </div>
    <button type="submit">Upload</button>
</form>
</body>
</html>